# Generated by Django 3.2.6 on 2022-09-24 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220922_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
